# 应用基础配置
app:
  name: "ChatAgent"
  version: "0.1.0"
  debug: true
  environment: "development"

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  workers: 1

# 数据库配置
database:
  url: "sqlite:///./data/chat_agent.db"
  echo: false
  pool_size: 5
  max_overflow: 10

# 安全配置
security:
  secret_key: "your-secret-key-here-change-in-production"
  algorithm: "HS256"
  access_token_expire_minutes: 30

# 向量数据库配置
vector_db:
  type: "chroma"  # chroma, faiss
  chroma:
    persist_directory: "./data/chroma"
    collection_name: "documents"
  embedding:
    provider: "zhipu"  # openai, zhipu, sentence-transformers
    model: "embedding-3"
    dimension: 1024

# 文件处理配置
file:
  upload_dir: "./data/uploads"
  max_size: 10485760  # 10MB
  allowed_extensions: [".txt", ".pdf", ".docx", ".md"]
  chunk_size: 1000
  chunk_overlap: 200

# 日志配置
logging:
  level: "INFO"
  file: "./data/logs/app.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# CORS配置
cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "*"

# 知识库配置
knowledge_base:
  default_kb: "default"
  max_search_results: 5
  similarity_threshold: 0.7

# 对话配置
chat:
  max_history_length: 10
  system_prompt: "你是一个有用的AI助手，请根据提供的上下文信息回答用户的问题。"
  max_response_tokens: 1000